### ISSUE TITLE
create different versions based on the wished version of cache tool

### ISSUE THREAD

**Issue by bertBruynooghe** [tijsverkoyen/capistrano-cachetool#7]
Latest version of the cache tool (which is taken automatically) does not work with PHP7, making impossible to make deploys of older codebases. Making different versions of the tool, or at least hard choosing a cache tool version would solve this. 
(To get around this, I had to fork the project and hardcode the version myself)

**Comment by tijsverkoyen** [comment]
@bertBruynooghe Can't you use
`set :cachetool_download_url, 'https://gordalina.github.io/cachetool/downloads/cachetool-3.2.2.phar'`
